vim.g.mapleader = "\\"

-- General
vim.keymap.set('v', '<Leader>p', '"_dP')
vim.keymap.set('n', '<Leader>bb', ':buffers<CR>:buffer<Space>')
vim.keymap.set('n', '<Leader>bd', ':buffers<CR>:bdelete<Space>')
vim.keymap.set('n', '[b', ':bprevious<CR>')
vim.keymap.set('n', ']b', ':bnext<CR>')
vim.keymap.set('n', ']q', ':cnext<CR>')
vim.keymap.set('n', ']Q', ':clast<CR>')
vim.keymap.set('n', '[q', ':cprevious<CR>')
vim.keymap.set('n', '[Q', ':cfirst<CR>')
vim.keymap.set('n', ']l', ':lnext<CR>')
vim.keymap.set('n', ']L', ':llast<CR>')
vim.keymap.set('n', '[l', ':lprevious<CR>')
vim.keymap.set('n', '[L', ':lfirst<CR>')
vim.keymap.set('n', ']a', ':next<CR>')
vim.keymap.set('n', ']A', ':last<CR>')
vim.keymap.set('n', '[a', ':previous<CR>')
vim.keymap.set('n', '[A', ':first<CR>')
vim.keymap.set('n', '<leader>h', vim.diagnostic.open_float)
vim.keymap.set('n', '<leader>H', vim.diagnostic.setloclist)
vim.keymap.set('n', '[h', vim.diagnostic.goto_prev)
vim.keymap.set('n', ']h', vim.diagnostic.goto_next)
vim.keymap.set('n', '-', ':Explore<CR>')
vim.keymap.set('n', '<Leader>-', ':Explore.<CR>')

-- Telescope
vim.keymap.set('n', '<leader>tf', ':Telescope find_files<CR>')
vim.keymap.set('n', '<leader>tg', ':Telescope live_grep<CR>')
vim.keymap.set('n', '<leader>tb', ':Telescope buffers<CR>')
vim.keymap.set('n', '<leader>th', ':Telescope help_tags<CR>')
vim.keymap.set('n', '<leader>ts', ':Telescope lsp_workspace_symbols<CR>')
